### ISSUE TITLE
Prometheus-Sample-App gauge metric value only goes up

### ISSUE THREAD

**Issue by mustafain117** [open-o11y/prometheus-sample-app#7]
**Describe the bug**

Prometheus gauge metric represents value that can go up and down. However, Gauge metric produced by this app currently only goes up.

**What did you expect to see?**

Expected to see gauge value go both up and down instead of being monotonically increasing.

**Possible Solution**

In function [updateGauge()](https://github.com/open-o11y/prometheus-sample-app/blob/e1f26c81acafc293cb23932137e05e031f85779a/metrics/metrics_collector.go#L36) to `c.Set(rand.Float64())`. This should make gauge value go both ways - up and down.

**Additional context**
Related to open-telemetry/wg-prometheus#57
cc @alolita @Aneurysm9

**Comment by PaurushGarg** [comment]
Merged as part of PR #11
